export const translations = {
  en: {
    appName: "EVM Simulator", settings: "Settings", newElection: "New Election", recentElections: "Recent Elections", noElections: "No elections found. Start a new one!", completed: "Completed", active: "Active", candidates: "Candidates", appearance: "APPEARANCE", darkMode: "Dark Mode", language: "Language", dataManagement: "DATA MANAGEMENT", clearData: "Clear All Elections Data", aboutDev: "ABOUT DEVELOPER", helpInfo: "HELP & INFO", appVersion: "App Version", electionName: "Election Name", addCandidate: "Add Candidate", advancedOptions: "Advanced Options", saveElection: "Save Election", totalVoters: "Total Voters", unlockEvm: "Unlock EVM", clearMock: "Clear (Mock Poll)", closeElection: "Close Election", electionResult: "Election Result", shareResult: "Share Result", winner: "Winner", tie: "TIE!", exSchoolElec: "Ex: School Election 2026", candidateText: "Candidate", timeSchedule: "Time Schedule (Optional)", voteStartTime: "Voting Start Time", noTimeLimit: "No Time Limit", voteEndTime: "Voting End Time", resultTimeText: "Result Time", viewInstantly: "View Instantly", totalVotersOpt: "Total Voters (Optional)", selectTime: "Select Time", errorText: "Error", successText: "Success", warningText: "Warning", namePinReq: "Name and PIN are required!", pinMismatch: "PINs do not match!", savedSuccess: "Election saved successfully!", saveFailed: "Could not save election!", min2Cand: "Minimum 2 candidates required!", resultCountdown: "Result will be published in:", days: "Days", hours: "Hrs", mins: "Mins", secs: "Secs", waitResult: "Please wait until the result time.",
    welcomeDesc: "This app helps you understand how the Indian election process and Electronic Voting Machines (EVM) work.", feature1: "Add candidates and symbols to conduct your own mock elections.", feature2: "Learn the real working of Control Unit and Ballot Unit.", feature3: "100% Offline. No internet connection required.", getStarted: "Get Started",
    cuLocked: "Control Unit Locked", enterPinToUnlock: "Enter PIN to unlock", wrongPin: "Wrong PIN!", cancel: "Cancel", cuTitle: "Control Unit (CU)", votesPolled: "VOTES POLLED", unlockBu: "UNLOCK BALLOT UNIT", enterPinToVote: "Enter PIN to allow voting", closeWarning: "Are you sure? No more voting allowed.", clearWarning: "All votes will be erased. Continue?", votesCleared: "Votes cleared!", deleteConfirm: "This election will be deleted. Continue?", delete: "Delete",
    limitReached: "Maximum voter limit reached! No more votes can be polled."
  },
  ml: {
    appName: "ഇവിഎം സിമുലേറ്റർ", settings: "സെറ്റിംഗ്സ്", newElection: "പുതിയ ഇലക്ഷൻ", recentElections: "സമീപകാല ഇലക്ഷനുകൾ", noElections: "ഇലക്ഷനുകൾ ഒന്നുമില്ല. പുതിയൊരെണ്ണം തുടങ്ങുക!", completed: "പൂർത്തിയായി", active: "സജീവമാണ്", candidates: "സ്ഥാനാർത്ഥികൾ", appearance: "രൂപകൽപ്പന (APPEARANCE)", darkMode: "ഡാർക്ക് മോഡ്", language: "ഭാഷ (Language)", dataManagement: "ഡാറ്റ മാനേജ്മെന്റ്", clearData: "എല്ലാ ഡാറ്റയും മായ്ക്കുക", aboutDev: "ഡെവലപ്പറെക്കുറിച്ച്", helpInfo: "സഹായവും വിവരങ്ങളും", appVersion: "ആപ്പ് വേർഷൻ", electionName: "ഇലക്ഷന്റെ പേര്", addCandidate: "സ്ഥാനാർത്ഥികൾ", advancedOptions: "അഡ്വാൻസ്ഡ് ഓപ്ഷൻസ്", saveElection: "ഇലക്ഷൻ സേവ് ചെയ്യുക", totalVoters: "ആകെ വോട്ടർമാർ", unlockEvm: "അൺലോക്ക് (Unlock)", clearMock: "മായ്ക്കുക (Clear)", closeElection: "അവസാനിപ്പിക്കുക (Close)", electionResult: "തിരഞ്ഞെടുപ്പ് ഫലം", shareResult: "ഷെയർ ചെയ്യുക (Share)", winner: "വിജയി", tie: "സമനില (TIE)", exSchoolElec: "ഉദാ: സ്കൂൾ ഇലക്ഷൻ 2026", candidateText: "സ്ഥാനാർത്ഥി", timeSchedule: "സമയക്രമം (നിർബന്ധമല്ല)", voteStartTime: "വോട്ടിംഗ് തുടങ്ങുന്ന സമയം", noTimeLimit: "സമയപരിധി വേണ്ട", voteEndTime: "വോട്ടിംഗ് അവസാനിക്കുന്ന സമയം", resultTimeText: "റിസൾട്ട് സമയം", viewInstantly: "ഉടൻ റിസൾട്ട് കാണാം", totalVotersOpt: "ആകെ വോട്ടർമാർ (Optional)", selectTime: "സമയം തിരഞ്ഞെടുക്കുക", errorText: "പിശക്", successText: "വിജയിച്ചു", warningText: "മുന്നറിയിപ്പ്", namePinReq: "പേരും PIN ഉം നിർബന്ധമാണ്!", pinMismatch: "PIN പൊരുത്തപ്പെടുന്നില്ല!", savedSuccess: "ഇലക്ഷൻ വിജയകരമായി സേവ് ചെയ്തു!", saveFailed: "സേവ് ചെയ്യാൻ കഴിഞ്ഞില്ല!", min2Cand: "കുറഞ്ഞത് 2 സ്ഥാനാർത്ഥികൾ എങ്കിലും വേണം!", resultCountdown: "റിസൾട്ട് വരാൻ ഇനി:", days: "ദിവസം", hours: "മണിക്കൂർ", mins: "മിനിറ്റ്", secs: "സെക്കൻഡ്", waitResult: "റിസൾട്ട് സമയം ആകുന്നത് വരെ ദയവായി കാത്തിരിക്കുക.",
    welcomeDesc: "ഇന്ത്യൻ തിരഞ്ഞെടുപ്പ് പ്രക്രിയയും വോട്ടിംഗ് മെഷീനും (EVM) എങ്ങനെ പ്രവർത്തിക്കുന്നു എന്ന് മനസ്സിലാക്കാൻ ഈ ആപ്പ് സഹായിക്കും.", feature1: "സ്ഥാനാർത്ഥികളെയും ചിഹ്നങ്ങളെയും ചേർത്ത് സ്വന്തമായി തിരഞ്ഞെടുപ്പ് നടത്താം.", feature2: "Control Unit, Ballot Unit എന്നിവയുടെ യഥാർത്ഥ പ്രവർത്തനം പഠിക്കാം.", feature3: "100% Offline. ഇന്റർനെറ്റ് ആവശ്യമില്ല.", getStarted: "തുടങ്ങാം",
    cuLocked: "കൺട്രോൾ യൂണിറ്റ് ലോക്ക് ചെയ്തു", enterPinToUnlock: "തുറക്കാൻ PIN നൽകുക", wrongPin: "തെറ്റായ PIN!", cancel: "ക്യാൻസൽ", cuTitle: "കൺട്രോൾ യൂണിറ്റ് (CU)", votesPolled: "പോൾ ചെയ്ത വോട്ടുകൾ", unlockBu: "ബാലറ്റ് അൺലോക്ക് ചെയ്യുക", enterPinToVote: "വോട്ട് ചെയ്യാൻ PIN നൽകുക", closeWarning: "ഉറപ്പാണോ? പിന്നീട് വോട്ട് ചെയ്യാൻ കഴിയില്ല.", clearWarning: "എല്ലാ വോട്ടുകളും മാഞ്ഞുപോകും. തുടരണോ?", votesCleared: "വോട്ടുകൾ മായ്ച്ചു!", deleteConfirm: "ഈ ഇലക്ഷൻ ഡിലീറ്റ് ആകും. തുടരണോ?", delete: "ഡിലീറ്റ്",
    limitReached: "വോട്ടർമാരുടെ എണ്ണം തികഞ്ഞു! ഇനി വോട്ട് ചെയ്യാൻ കഴിയില്ല."
  }
};
